services:

  # Reference: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    ports:
      - "8888:8000"
    working_dir: /home/dynamodblocal